[2023-09-07T17:32:52.343+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.create_data_table manual__2023-09-07T17:32:49.196342+00:00 [queued]>
[2023-09-07T17:32:52.361+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.create_data_table manual__2023-09-07T17:32:49.196342+00:00 [queued]>
[2023-09-07T17:32:52.364+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-07T17:32:52.383+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_data_table> on 2023-09-07 17:32:49.196342+00:00
[2023-09-07T17:32:52.409+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2023-09-07T17:32:52.419+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'create_data_table', 'manual__2023-09-07T17:32:49.196342+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_log_into_postgres.py', '--cfg-path', '/tmp/tmpf9epa15f']
[2023-09-07T17:32:52.430+0000] {standard_task_runner.py:85} INFO - Job 345: Subtask create_data_table
[2023-09-07T17:32:52.566+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.create_data_table manual__2023-09-07T17:32:49.196342+00:00 [running]> on host 533d17d76452
[2023-09-07T17:32:52.730+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='create_data_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-07T17:32:49.196342+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-07T17:32:49.196342+00:00'
[2023-09-07T17:32:52.734+0000] {sql.py:274} INFO - Executing: -- create data table
create_data_table = """
            CREATE TABLE IF NOT EXISTS test2(
            title CHAR(5000) NOT NULL,
            author CHAR(5000) NOT NULL,
            date CHAR(5000) NOT NULL,
            time CHAR(5000) NOT NULL,
            summary CHAR(5000) NOT NULL);
          """
[2023-09-07T17:32:52.767+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-09-07T17:32:52.801+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-09-07T17:32:52.809+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-09-07T17:32:52.842+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=create_data_table, execution_date=20230907T173249, start_date=20230907T173252, end_date=20230907T173252
[2023-09-07T17:32:52.862+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 345 for task create_data_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 57)
[2023-09-07T17:32:52.917+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-07T17:32:53.011+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
