[2023-09-07T15:12:45.820+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.create_data_table manual__2023-09-07T15:12:44.111927+00:00 [queued]>
[2023-09-07T15:12:45.842+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.create_data_table manual__2023-09-07T15:12:44.111927+00:00 [queued]>
[2023-09-07T15:12:45.846+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-07T15:12:45.923+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_data_table> on 2023-09-07 15:12:44.111927+00:00
[2023-09-07T15:12:45.986+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2023-09-07T15:12:46.008+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'create_data_table', 'manual__2023-09-07T15:12:44.111927+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_log_into_postgres.py', '--cfg-path', '/tmp/tmpydnx490u']
[2023-09-07T15:12:46.031+0000] {standard_task_runner.py:85} INFO - Job 324: Subtask create_data_table
[2023-09-07T15:12:46.298+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.create_data_table manual__2023-09-07T15:12:44.111927+00:00 [running]> on host 533d17d76452
[2023-09-07T15:12:46.511+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='create_data_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-07T15:12:44.111927+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-07T15:12:44.111927+00:00'
[2023-09-07T15:12:46.515+0000] {sql.py:274} INFO - Executing: -- create data table
create_data_table = """
            CREATE TABLE IF NOT EXISTS test2(
            title CHAR(5000) NOT NULL,
            author CHAR(5000) NOT NULL,
            date CHAR(5000) NOT NULL,
            time CHAR(5000) NOT NULL,
            summary CHAR(5000) NOT NULL);
          """
[2023-09-07T15:12:46.533+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-09-07T15:12:46.553+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-09-07T15:12:46.556+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-09-07T15:12:46.577+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=create_data_table, execution_date=20230907T151244, start_date=20230907T151245, end_date=20230907T151246
[2023-09-07T15:12:46.592+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 324 for task create_data_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 63)
[2023-09-07T15:12:46.637+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-07T15:12:46.670+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
