[2023-09-07T14:34:17.030+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.create_data_table manual__2023-09-07T14:33:17.751766+00:00 [queued]>
[2023-09-07T14:34:17.040+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.create_data_table manual__2023-09-07T14:33:17.751766+00:00 [queued]>
[2023-09-07T14:34:17.041+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2023-09-07T14:34:17.053+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_data_table> on 2023-09-07 14:33:17.751766+00:00
[2023-09-07T14:34:17.060+0000] {standard_task_runner.py:57} INFO - Started process 77 to run task
[2023-09-07T14:34:17.067+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'create_data_table', 'manual__2023-09-07T14:33:17.751766+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_log_into_postgres.py', '--cfg-path', '/tmp/tmp95plknna']
[2023-09-07T14:34:17.075+0000] {standard_task_runner.py:85} INFO - Job 312: Subtask create_data_table
[2023-09-07T14:34:17.143+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.create_data_table manual__2023-09-07T14:33:17.751766+00:00 [running]> on host 533d17d76452
[2023-09-07T14:34:17.230+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='create_data_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-07T14:33:17.751766+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-07T14:33:17.751766+00:00'
[2023-09-07T14:34:17.233+0000] {sql.py:274} INFO - Executing: -- create data table
create_data_table = """
            CREATE TABLE IF NOT EXISTS test2(
            title CHAR(5000) NOT NULL,
            author CHAR(5000) NOT NULL,
            date CHAR(5000) NOT NULL,
            time CHAR(5000) NOT NULL,
            summary CHAR(5000) NOT NULL);
          """
[2023-09-07T14:34:17.250+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-09-07T14:34:17.274+0000] {base.py:73} INFO - Using connection ID 'postgres_local' for task execution.
[2023-09-07T14:34:17.278+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-09-07T14:34:17.293+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=create_data_table, execution_date=20230907T143317, start_date=20230907T143417, end_date=20230907T143417
[2023-09-07T14:34:17.305+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 312 for task create_data_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 77)
[2023-09-07T14:34:17.320+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-07T14:34:17.345+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
