[2023-09-02T13:26:34.744+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.crawl_task manual__2023-09-02T13:26:10.613607+00:00 [queued]>
[2023-09-02T13:26:34.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.crawl_task manual__2023-09-02T13:26:10.613607+00:00 [queued]>
[2023-09-02T13:26:34.760+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-02T13:26:34.775+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_task> on 2023-09-02 13:26:10.613607+00:00
[2023-09-02T13:26:34.783+0000] {standard_task_runner.py:57} INFO - Started process 47 to run task
[2023-09-02T13:26:34.792+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'crawl_task', 'manual__2023-09-02T13:26:10.613607+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmpyqq6fhnj']
[2023-09-02T13:26:34.803+0000] {standard_task_runner.py:85} INFO - Job 265: Subtask crawl_task
[2023-09-02T13:26:34.892+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.crawl_task manual__2023-09-02T13:26:10.613607+00:00 [running]> on host 9b7e267dee3b
[2023-09-02T13:26:35.007+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='crawl_task' AIRFLOW_CTX_EXECUTION_DATE='2023-09-02T13:26:10.613607+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-02T13:26:10.613607+00:00'
[2023-09-02T13:26:35.721+0000] {crawl_data_using_BeautifulSoup.py:89} INFO - test abc
[2023-09-02T13:26:36.222+0000] {crawl_data_using_BeautifulSoup.py:99} INFO - test bcd
[2023-09-02T13:26:36.229+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawl_data_using_BeautifulSoup.py", line 106, in crawl_section_pages
    json.dump(json_data, log_file, indent=4, ensure_ascii=False)
NameError: name 'json' is not defined
[2023-09-02T13:26:36.278+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=crawl_task, execution_date=20230902T132610, start_date=20230902T132634, end_date=20230902T132636
[2023-09-02T13:26:36.310+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 265 for task crawl_task (name 'json' is not defined; 47)
[2023-09-02T13:26:36.391+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-02T13:26:36.452+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
