[2023-08-31T03:40:59.974+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.crawl_task scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2023-08-31T03:40:59.987+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.crawl_task scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2023-08-31T03:40:59.989+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-31T03:41:00.026+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_task> on 2023-08-29 00:00:00+00:00
[2023-08-31T03:41:00.041+0000] {standard_task_runner.py:57} INFO - Started process 52 to run task
[2023-08-31T03:41:00.058+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'crawl_task', 'scheduled__2023-08-29T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmp1lr60bno']
[2023-08-31T03:41:00.065+0000] {standard_task_runner.py:85} INFO - Job 146: Subtask crawl_task
[2023-08-31T03:41:00.280+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.crawl_task scheduled__2023-08-29T00:00:00+00:00 [running]> on host b053bf73ca11
[2023-08-31T03:41:00.621+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='crawl_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T00:00:00+00:00'
[2023-08-31T03:41:01.364+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawl_data_using_BeautifulSoup.py", line 50, in crawl_section_pages
    file_handler = logging.FileHandler('/Users/nguyenngocanh/Desktop/cohost AI/logs/test.txt')
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nguyenngocanh/Desktop/cohost AI/logs/test.txt'
[2023-08-31T03:41:01.402+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=crawl_task, execution_date=20230829T000000, start_date=20230831T034059, end_date=20230831T034101
[2023-08-31T03:41:01.427+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 146 for task crawl_task ([Errno 2] No such file or directory: '/Users/nguyenngocanh/Desktop/cohost AI/logs/test.txt'; 52)
[2023-08-31T03:41:01.480+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-31T03:41:01.532+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-02T10:13:11.999+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.crawl_task scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2023-09-02T10:13:13.106+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.crawl_task scheduled__2023-08-29T00:00:00+00:00 [queued]>
[2023-09-02T10:13:13.133+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-02T10:13:14.059+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_task> on 2023-08-29 00:00:00+00:00
[2023-09-02T10:13:14.412+0000] {standard_task_runner.py:57} INFO - Started process 72 to run task
[2023-09-02T10:13:14.741+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'crawl_task', 'scheduled__2023-08-29T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmpuffl7_f3']
[2023-09-02T10:13:15.083+0000] {standard_task_runner.py:85} INFO - Job 250: Subtask crawl_task
[2023-09-02T10:13:18.755+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.crawl_task scheduled__2023-08-29T00:00:00+00:00 [running]> on host 9b7e267dee3b
[2023-09-02T10:13:25.701+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='crawl_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T00:00:00+00:00'
[2023-09-02T10:13:44.588+0000] {local_task_job_runner.py:288} WARNING - DagRun timed out after 0:01:11.551460.
[2023-09-02T10:14:07.899+0000] {local_task_job_runner.py:288} WARNING - DagRun timed out after 0:01:34.919681.
[2023-09-02T10:14:09.554+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2023-09-02T10:14:11.667+0000] {process_utils.py:131} INFO - Sending 15 to group 72. PIDs of all processes in the group: [72]
[2023-09-02T10:14:17.313+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 72
[2023-09-02T10:14:17.642+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-09-02T10:14:20.019+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=72, status='terminated', exitcode=0, started='10:13:14') (72) terminated with exit code 0
