[2023-09-01T23:33:23.443+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.write_to_file manual__2023-09-01T23:33:09.380267+00:00 [queued]>
[2023-09-01T23:33:23.460+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.write_to_file manual__2023-09-01T23:33:09.380267+00:00 [queued]>
[2023-09-01T23:33:23.465+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-01T23:33:23.492+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): write_to_file> on 2023-09-01 23:33:09.380267+00:00
[2023-09-01T23:33:23.511+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2023-09-01T23:33:23.527+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'write_to_file', 'manual__2023-09-01T23:33:09.380267+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmpo0zp7j8y']
[2023-09-01T23:33:23.534+0000] {standard_task_runner.py:85} INFO - Job 198: Subtask write_to_file
[2023-09-01T23:33:23.643+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.write_to_file manual__2023-09-01T23:33:09.380267+00:00 [running]> on host 200bc7f91af2
[2023-09-01T23:33:23.738+0000] {abstractoperator.py:696} ERROR - Exception rendering Jinja template for task 'write_to_file', field 'bash_command'. Template: "\n    touch /usr/local/***/dags/{{test}}.txt\n    echo {{ti.xcom_pull(task_ids='crawl_task')}} > /usr/local/***/dags/{{test}}.txt\n    "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 688, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 642, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'test' is undefined
[2023-09-01T23:33:23.750+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1646, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2291, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1244, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 688, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 642, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'test' is undefined
[2023-09-01T23:33:23.792+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=write_to_file, execution_date=20230901T233309, start_date=20230901T233323, end_date=20230901T233323
[2023-09-01T23:33:23.841+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 198 for task write_to_file ('test' is undefined; 74)
[2023-09-01T23:33:23.905+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T23:33:23.937+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
