[2023-09-01T23:38:57.585+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.write_to_file manual__2023-09-01T23:38:43.044493+00:00 [queued]>
[2023-09-01T23:38:57.597+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.write_to_file manual__2023-09-01T23:38:43.044493+00:00 [queued]>
[2023-09-01T23:38:57.608+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-09-01T23:38:57.623+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): write_to_file> on 2023-09-01 23:38:43.044493+00:00
[2023-09-01T23:38:57.629+0000] {standard_task_runner.py:57} INFO - Started process 56 to run task
[2023-09-01T23:38:57.638+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'write_to_file', 'manual__2023-09-01T23:38:43.044493+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmp_vir970u']
[2023-09-01T23:38:57.646+0000] {standard_task_runner.py:85} INFO - Job 202: Subtask write_to_file
[2023-09-01T23:38:57.732+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.write_to_file manual__2023-09-01T23:38:43.044493+00:00 [running]> on host 200bc7f91af2
[2023-09-01T23:38:57.850+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='write_to_file' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T23:38:43.044493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-01T23:38:43.044493+00:00'
[2023-09-01T23:38:57.869+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-01T23:38:57.871+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    touch /usr/local/***/dags/test.txt\n    echo abc > /usr/local/***/dags/test.txt\n    ']
[2023-09-01T23:38:57.897+0000] {subprocess.py:86} INFO - Output:
[2023-09-01T23:38:57.931+0000] {subprocess.py:93} INFO - touch: cannot touch '/usr/local/***/dags/test.txt': No such file or directory
[2023-09-01T23:38:57.934+0000] {subprocess.py:93} INFO - /bin/bash: line 3: /usr/local/***/dags/test.txt: No such file or directory
[2023-09-01T23:38:57.936+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-01T23:38:57.962+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-01T23:38:57.968+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=write_to_file, execution_date=20230901T233843, start_date=20230901T233857, end_date=20230901T233857
[2023-09-01T23:38:57.982+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 202 for task write_to_file (Bash command failed. The command returned a non-zero exit code 1.; 56)
[2023-09-01T23:38:58.011+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T23:38:58.033+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
