[2023-08-31T05:11:17.665+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.write_to_file manual__2023-08-31T05:11:03.497904+00:00 [queued]>
[2023-08-31T05:11:17.675+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.write_to_file manual__2023-08-31T05:11:03.497904+00:00 [queued]>
[2023-08-31T05:11:17.676+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-31T05:11:17.689+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): write_to_file> on 2023-08-31 05:11:03.497904+00:00
[2023-08-31T05:11:17.698+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2023-08-31T05:11:17.705+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'write_to_file', 'manual__2023-08-31T05:11:03.497904+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmp0cbxc7yd']
[2023-08-31T05:11:17.712+0000] {standard_task_runner.py:85} INFO - Job 177: Subtask write_to_file
[2023-08-31T05:11:17.787+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.write_to_file manual__2023-08-31T05:11:03.497904+00:00 [running]> on host b053bf73ca11
[2023-08-31T05:11:17.905+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='write_to_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T05:11:03.497904+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T05:11:03.497904+00:00'
[2023-08-31T05:11:17.911+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-31T05:11:17.913+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    touch /Users/nguyenngocanh/Desktop/cohost AI/logs/test.txt\n    echo abc > /Users/nguyenngocanh/Desktop/cohost AI/logs/test.txt\n    ']
[2023-08-31T05:11:17.931+0000] {subprocess.py:86} INFO - Output:
[2023-08-31T05:11:17.947+0000] {subprocess.py:93} INFO - touch: cannot touch '/Users/nguyenngocanh/Desktop/cohost': No such file or directory
[2023-08-31T05:11:17.948+0000] {subprocess.py:93} INFO - touch: cannot touch 'AI/logs/test.txt': No such file or directory
[2023-08-31T05:11:17.950+0000] {subprocess.py:93} INFO - /bin/bash: line 3: /Users/nguyenngocanh/Desktop/cohost: No such file or directory
[2023-08-31T05:11:17.952+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-31T05:11:17.971+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-31T05:11:17.976+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=write_to_file, execution_date=20230831T051103, start_date=20230831T051117, end_date=20230831T051117
[2023-08-31T05:11:17.991+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 177 for task write_to_file (Bash command failed. The command returned a non-zero exit code 1.; 114)
[2023-08-31T05:11:18.022+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-31T05:11:18.047+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
